### ISSUE TITLE
PayPal error code: 10401 - Order total is invalid

### ISSUE THREAD

**Issue by leo-mck** [davidduffett/Moolah#10]
First, thank you for this library and sorry for my bad english...
When I call 

``` csharp
var response = gateway.SetExpressCheckout(5.00m, CurrencyCodeType.BRL, cancelUrl, confirmationUrl);
```

I get the response:

_"PayPal error code: 10401
Short message: Transaction refused because of an invalid argument. See additional error messages for details.
Long message: Order total is invalid."_

Am I forgeting something?

**Comment by davidduffett** [comment]
Hmm... I have an integration test for that API call that is not failing - can you check your PayPal configuration?  Are you running in the sandbox or a live environment?

**Comment by davidduffett** [comment]
A proposito, voce e brasileiro?  Podemos conversar em portugues tambem se voce quiser.

**Comment by leo-mck** [comment]
Olá David, sou brasileiro sim :D - estou tentando no ambiente de produção (live)... a única coisa estranha que achei nas configurações do paypal é que o tipo de minha conta é "especial" (devo ter mudado isso em algum momento, e agora não posso mais mudar). Revirei as configurações para ver se há alguma outra coisa que possa ser a causa do problema mas não encontrei. O acesso a API está habilitado. Caso eu utilize um botão do paypal, funciona, então o problema parece mesmo ser algo nas configurações da API... também tentei com outros valores e moedas, sem sucesso. Já tentei especificar o item detalhadamente com o valor, quantidade corretas mas ocorre o mesmo erro. 
O mesmo teste no ambiente de testes causa o mesmo erro. Devo estar esquecendo da configurar algo no paypal mas não consigo encontrar o que é :(

**Comment by davidduffett** [comment]
Oi Leo - desculpe pelo atraso na resposta - eu estou preparando para o meu
casamento e nao tive a oportunidade de investigar o seu problema.

Voce pode por favor provar o outro method com order details?  Talvez e um
problema so com passando "amount" sem "order details"...?

SetExpressCheckout(OrderDetails orderDetails, string cancelUrl, string
confirmationUrl);

2012/10/10 Leo notifications@github.com

**Comment by leo-mck** [comment]
Olá David, parabéns pelo casamento! 
Já havia tentado o método especificando o Order details e ocorria o mesmo erro... mas fiz mais alguns testes e encontrei uma solução, o problema é causado pela formatação dos valores, no locale pt-BR, é usado "," como divisor decimal (ex.: 1.000,50). Isso, aparentemente está causando o problema... bastou eu chamar 

Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US"); 

antes de chamar SetExpressCheckout e funcionou perfeitamente :D

Obrigado pela ajuda.

**Comment by fnicollier** [comment]
Actually pull request #31 fixes this issue. We had the same problem with French culture. No need to change the thread's culture anymore as Moolah will ignore it now.
