### ISSUE TITLE
No order summary info on Paypal Express Checkout

### ISSUE THREAD

**Issue by snuffler71** [davidduffett/Moolah#2]
Hi there, it;s working relly well, other than there is no price info in Order summary on paypal checkout. I've tried:

var orderDetails = new OrderDetails {OrderTotal = price};
 var response = gateway.SetExpressCheckout(orderDetails, cancelUrl, confirmationUrl);

and

var response = gateway.SetExpressCheckout(12.99m, cancelUrl, confirmationUrl);

Regards,
Graham

**Comment by davidduffett** [comment]
Hi Graham

When you only supply an amount to PayPal it only displays "Current purchase" and "You'll be able to see your order details before you pay." in the order summary box.  This, unfortunately, is what PayPal does!

I would suggest filling in all of the order line details if you can, that way you get a full order summary, including price info.  You can do this by populating the Items collection on OrderDetails.

If you want any further help please let me know!

Dave

**Comment by snuffler71** [comment]
Many thanks David, I'll gve that shot.

Regards,
Graham

On Tue, Apr 3, 2012 at 9:00 AM, David Duffett
reply@reply.github.com
wrote:

**Comment by snuffler71** [comment]
That worked a treat David, thank you

**Comment by davidduffett** [comment]
@snuffler71 Just to let you know I've just released a new version which incorporates a new DoExpressCheckoutPayment method, which accepts all order details (in the same way as SetExpressCheckout does).

This is optional - you can still confirm payment with just an amount.  The reason for adding it is that if you only confirm payment with an amount, all previous order details are not shown on the PayPal invoice email sent to the customer.

Re-sending all the order details again ensures that they are shown on the PayPal invoice.

You would think that PayPal would remember the order details based on the token, but hey-ho, they don't!

**Comment by shehzadvbase** [comment]
I hope this will help you it worked for me.

```
        Invoice inv = new Invoice();
        Currency amt = new Currency(new Double("2000.00"), "USD");
        inv.setAmt(amt);
        inv.setOrderDesc("This is optional description");

        // Create a line item.
        // Suppose there are two list items and each item have quentity 10
        //Add first item in order summary
        LineItem item = new LineItem();
        Currency amt1 = new Currency(1000.00), "USD");
        item.setAmt(amt1);
        item.setDesc("Item one desc");
        item.setQty(10);
        item.setCost(new Currency(100.00), "USD"));         
        inv.addLineItem(item);

        //Add second item in order summary
        LineItem item2 = new LineItem();
        Currency amt2 = new Currency(1000.00), "USD");
        item2.setAmt(amt2);
        item2.setDesc("Item two desc");
        item2.setQty(10);
        item2.setCost(new Currency(100.00), "USD"));            
        inv.addLineItem(item2);
```

Rest of the request is same.
