### ISSUE TITLE
Shipping Country Code

### ISSUE THREAD

**Issue by johncdoherty** [davidduffett/Moolah#25]
Hi, I've been using the framework seamlessly to accept PayPal payments for the last week (thanks, it's really helpful!), but recently I tried to add a shipping cost to my items and I had an error. When my sandbox user logs in and attempts to pay, I receive the following error embedded on the PayPal page:
ASF::Client::ClientConnectException: Client received error with operation get_segments on service SegmentRead version 1.0 endpoint 10.72.108.213:10761 in state connect Backtrace: ASF::ASFException::ASFException(String const&) ASF::FrameworkException::FrameworkException(String const&) ASF::Client::ClientException::ClientException(String const&) ASF::Client::ClientConnectException::ClientConnectException(String const&) ASF::Client::Client::check_error(ASF::Protocol::HttpClientProcessor_, char const_) ASF::Client::Client::send_request(char const_, ValueObject const&, bool, bool, bool) ASF::Client::Client::invoke_operation(char const_, ValueObject const&, ValueObject&, bool) Marketing::SegmentReadClient::get_segments(Marketing::GetSegmentsRequest const&, Marketing::GetSegmentsResponse&) FundingMix::DeferredPaymentSystemBLIImpl::is_user_in_pad_allowed_segment(unsigned long long) Rapids::Flows::FundingMix::DecoratorPADToggle::prepare_page() Rapids::DecoratedState::prepare_page() Riprap::RiprapRapidsGenericFlow::handle_prepare_page(Riprap::WebAppContextOrnate const&, bool&, Rapids::TransitionEdge&) Riprap::RiprapRapidsGenericFlow::handle_transition(Riprap::WebAppContextOrnate const&, Rapids::TransitionEdge const&, String const&, bool&, Riprap::RiprapRapidsGenericFlow::ProcessStates&, Riprap::DispatchInterceptorRegistry const&) Riprap::RiprapRapidsGenericFlow::process_states(Riprap::WebAppContextOrnate const&, Riprap::RiprapRapidsGenericFlow::ProcessStates, Riprap::DispatchInterceptorRegistry const&, Rapids::TransitionEdge const*) Riprap::RiprapRapidsGenericFlow::flow_return(Riprap::WebAppContextOrnate const&, Riprap::WebAppReturn const&, Riprap::DispatchInterceptorRegistry const&) Riprap::call_rapids(Riprap::WebAppContext const&, Riprap::RapidsFlowFactory const&, Riprap::DispatchAction const&, Riprap::WebAppReturn const&, String const&, Riprap::DispatchInterceptorRegistry const&) Riprap::dispatch_loop(Riprap::EPRegistry const&, Riprap::WebAppContext const&, Riprap::DispatchAction&, Riprap::WebAppReturn&, String const&, Riprap::DispatchInterceptorRegistry const&) Riprap::dispatch_wrapper(OutputStream&, Riprap::EPRegistry const&, Riprap::WebAppContext const&, Riprap::WebAppReturn const&, String const&, bool const&, Riprap::DispatchInterceptorRegistry const&) Riprap::entry_point(HTTPInterface&, Riprap::CGIVars&, OutputStream&, String const&, String const&) main
An error has occurred.

The page can be debugged, and it shows that there is a null value for the shipping country (I think) ... here's the line that complains:

/_9-US, 19-UK, 26-CA,37-DE,45-FR,52-IT,62-AU,72-ES,95-CN_/
shipping_co_id = YUD.get("markShippedUsing").value;

And here's the scripting error:

SCRIPT5007: Unable to get property 'value' of undefined or null reference 
merchantpaymentweb, line 135 character 15

Any ideas?
Thanks,
John

**Comment by davidduffett** [comment]
Hi John - I haven't come across this myself - Moolah doesn't actually pass any shipping address related information to PayPal, just a shipping charge and discount (if provided).

Is there any more information about the user account you were using that could cause this maybe? Have you been able to reliably reproduce it given certain data?

Cheers

**Comment by davidduffett** [comment]
Closing as I've heard no response.
