### ISSUE TITLE
paypal view order summary

### ISSUE THREAD

**Issue by kalyani11** [davidduffett/Moolah#28]
Hello!!!

i want to know this, when buyers will buy few items in my website 
when that press the button to pay they go to paypal but they don't see all the summary details...

well,Let me explain clearly...

i am developing my site in joomla 3.1.
for shopping cart i used j2store...
after proceed to pay i just directly link up to paypal page. but, in that, view order summary is not showing any thing.
now whats my problem is how can i get my j2store  order summary in paypal view order summary?

**Comment by davidduffett** [comment]
Are you using Moolah?  If you follow the instructions then all of the items should appear.  You need to POST to the PayPal URL rather than just link to it.

**Comment by davidduffett** [comment]
Closing as I've heard no response.
