### ISSUE TITLE
Docs for recurring payments

### ISSUE THREAD

**Issue by leo-mck** [davidduffett/Moolah#29]
How can I do a Paypal recursive payment with the library? There is some docs that I did not find somewhere?
Another thing, once a recurring payment is set, it is possible to cancel it with the library?

Thanks.

**Comment by davidduffett** [comment]
There are some integration tests here: https://github.com/davidduffett/Moolah/blob/master/Moolah/Moolah.Specs/PayPal/PayPalRecurringProfileIntegrationTest.cs

Essentially you add IsRecurringPayment = true to items included.

At present there isn't any way to cancel these recurring payments via Moolah - always open to a pull request though! :)
