### ISSUE TITLE
Doesn't Support Multiple Currencies

### ISSUE THREAD

**Issue by elacy** [davidduffett/Moolah#6]
It would be nice if it supported multiple currencies.
Our company allows people to pay in multiple currencies.

**Comment by davidduffett** [comment]
Would love to see this too - I'm scheduled to tackle multiple currencies towards the end of the year, if you can wait that long!  Otherwise, happy to receive contributions :-)

**Comment by elacy** [comment]
k

**Comment by davidduffett** [comment]
Note that this change only included PayPal - DataCash still doesn't support multi-currency.
